services:
  - type: web
    name: kc-cruizee-xmd
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_DIR
        value: ./storage/sessions
    autoDeploy: true
